modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="mcpaintball" #mandatory
version="1.0.0" #mandatory
displayName="MC Paintball" #mandatory
logoFile="examplemod.png" #optional
credits="" #optional
authors="Multicoder" #optional
description=''''''
[[dependencies.mcpaintball]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mcpaintball]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
